[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
android_logger = "0.13"
jni = "0.21"
log = "0.4"
rustix = { version = "0.38", default-features = false, features = ["std", "pipe", "stdio"] }