[package]
name = "native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21"
log = "0.4"
rustix = { version = "0.38", default-features = false, features = ["std", "pipe", "stdio"] }

leaf = { git = "https://github.com/shiroedev2024/leaf.git", branch = "master", default-features = false, features = ["default-ring"] }
doh = { git = "https://github.com/shiroedev2024/doh-client.git", branch = "master" , default-features = false }